version: "3.9"

services:
  db:
    image: postgres:latest
    hostname: db
    command: postgres -c 'max_connections=600'
    environment:
      - POSTGRES_PASSWORD=rinhav2
      - POSTGRES_USER=rinhav2
      - POSTGRES_DB=rinhav2////
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "0.4GB"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - app-network

networks:
  app-network: